[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Sven Hendrikx", email = "sven_hendrikx@hotmail.com"},
]
dependencies = []
requires-python = ">=3.10"
license = {text = "MIT"}
